name: Test ntfy Docker image (fix branches)

on:
  workflow_dispatch:      # manual run only

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # needed to push to ghcr.io

    steps:
      - name: Check out nightly-docker branch
        uses: actions/checkout@v4
        with:
          ref: nightly-docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push test Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-build
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ntfy:nightly-fixes

